### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by sjurgis** [benedwards44/sfswitch#1]
Few things to note:

Do not use Redis To Go, it does not work well with Celery. Go for Redis Micro ($5/month).

You'll need to setup SECRET_KEY in settings.py

There is some hard coded authors' org references, a.i. two instances of http://sfswitch.herokuapp.com/static/metadata-34.xml in tasks.py and some in /static/jquery-syntaxhighlighter/jquery.syntaxhighlighter.min.js

You'll need to build database via `heroku run python manage.py syncdb`

You'll need to enable workers in heroku dashboard.

You'll need to install Postgres, not Heroku database ;)

Cheers!

**Comment by benedwards44** [comment]
Sorry @sjurgis, only just saw this now. I've addressed the issues in your comments.

**Comment by jlondrejcka** [comment]
Ben, 

Your app is great. Just wondering if you know the cause of this error when trying to disable triggers: 
There was an error deploying your components: [Errno 39] Directory not empty: 'triggers'

Cheers, 

Joe

**Comment by benedwards44** [comment]
Finally add a (basic) README as well.
