### ISSUE TITLE
Source org where Connected App is created

### ISSUE THREAD

**Issue by awesomeandrey** [benedwards44/sfswitch#17]
Hi @benedwards44 

The tool is awesome, and undoubtedly useful for advanced SAs.

I just wanted to ask questions about implementation details. I'm not a Python developer unfortunately, and therefore I cannot completely 'understand' all the details of .py files.

There are 2 questions I would like to ask:

- Which OAuth flow do you use in the scope of 'sfswitch' app? 
- Did you create a dedicated Connected App in a separate Salesforce org you own? (Obviously, you have a separate salesforce org with connected app configured which comprises 'client_id' and 'client_secret' credentials, but I just want to confirm it with you).

Thanks in advanced

**Comment by benedwards44** [comment]
Hi @awesomeandrey 

To address your questions:

**1. Which OAuth flow do you use in the scope of 'sfswitch' app?**
The app (and all the toolkit apps actually) use the OAuth Web-Server flow:
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm&language=en_US&type=5

**2. Did you create a dedicated Connected App in a separate Salesforce org you own? (Obviously, you have a separate salesforce org with connected app configured which comprises 'client_id' and 'client_secret' credentials, but I just want to confirm it with you).**
Yes correct, I have a separate Connected App for each of the toolkit apps inside my own Dev Org. This holds the Client ID, Client Secret and scope for each application.

These are then stored securely server side within Heroku as environment variables for each app to use when authenticating between the applications and a user's own Salesforce Org.
