### ISSUE TITLE
[Errno 39] Directory not empty: 'triggers'

### ISSUE THREAD

**Issue by jlondrejcka** [benedwards44/sfswitch#2]
Ben, 

Your app is great, and I have been using it for a while. Just trying to troubleshoot this error when trying to disable triggers:
"There was an error deploying your components: [Errno 39] Directory not empty: 'triggers'"

Any help would be much appreciated!

Cheers, 

Joe

**Comment by eofferma** [comment]
It maybe related with [this](https://github.com/benedwards44/sfswitch/blob/bee17c751e68ba3fe512404446fe77a7b0d8b14a/enable_disable/tasks.py#L460) or [this](https://github.com/benedwards44/sfswitch/blob/bee17c751e68ba3fe512404446fe77a7b0d8b14a/enable_disable/tasks.py#L567) line.

Does it possible change these lines by this?

`import shutil`
`shutil.rmtree(dest, ignore_errors=True)`

Reference [here](http://stackoverflow.com/questions/303200/how-do-i-remove-delete-a-folder-that-is-not-empty-with-python).

Regards!

**Comment by benedwards44** [comment]
I believe it's to do with the `os.rmdir('triggers')` line, where it's trying to nuke the triggers folder (which is temporarily stored on the Heroku file system), but it's clearing it with files on it. I've put in place a process to remove the files as well. Should fix the issue.
