### ISSUE TITLE
triggers in production

### ISSUE THREAD

**Issue by MaggiePlusPlus** [benedwards44/sfswitch#6]
I know if I were to use the switch tool to disable a trigger in production that my tests would not pass as salesforce requires you to have a test for every trigger.  

Do you have a way to make this work? Maybe provide information for the user if so.

I do not need this as I have a way to turn my triggers off through custom metadata.  I suspect if I tried to run the tests with them disabled I would fail the 75% code coverage rule anyway.

**Comment by benedwards44** [comment]
@MaggiePlusPlus you're correct in that sense, and to be honest disabling triggers through this tool in Production probably isn't going to work.

Best practice is to use a Custom Setting (or Custom Metadata) to create toggles on each trigger to allow you to easily enable and disable them via the setup interface. For example:

```
if (Trigger_Manager__c.getInstance().Account__c) {
    // do trigger logic
}
```

In that sense, all your trigger logic (for every trigger) is wrapped in a custom setting checkbox, and you can easily disable the trigger.

**Comment by MaggiePlusPlus** [comment]
Yes as I said I do that. I guess what I was trying to say is that maybe your tool could mention this.  Admins that don't code will use your tool and get very frustrated when they have it set up to turn them off then try to deploy.  I think they will not understand why it isn't a good idea.
