### ISSUE TITLE
How to set local environment variables on Mac?

### ISSUE THREAD

**Issue by wr4909** [benedwards44/sfswitch#9]
Trying to run this locally. How do I let my local run see the environment variables?

I use Mac OS.

**Comment by benedwards44** [comment]
The environment variables are used for running on a server or on Heroku. You should be able to just edit the `settings.py` file and remove the environment variables and set the variables directly in the file.

**Comment by wr4909** [comment]
@benedwards44 Not entirely related to this, but when I run python manage.py collectstatic i get:
`whitenoise.storage.MissingFileError: The file 'admin/img/nav-bg.gif' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x1027efba8>.
`

Do you know how to fix this?
